
import Head from "next/head"
import { useForm, SubmitHandler } from "react-hook-form"
import { useRouter } from "next/router";
import { api } from "~/utils/api";

type AddArticleForm = {
    title: string;
    url: string;
    imageUrl: string;
    collection: string[]
  };
  
const AddAnArticle = ()=> {
   const {
        register,
        handleSubmit,
        watch,
        formState: { errors },
      } = useForm<AddArticleForm>()

      const onSubmit: SubmitHandler<AddArticleForm> = (data) => console.log(data)
    return(
        <>
        
<Head>
          <title></title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
       
            <h1 className="text-4xl"> nouvel article</h1>
            <form className="flex flex-col gap-6 p-6 bg-white shadow-md rounded-md" onSubmit={handleSubmit(onSubmit)}>

<div className="flex flex-col gap-2">
    <label htmlFor="title" className="text-lg font-semibold text-gray-900 dark:text-white">
        Title
    </label>
    <input id="title" placeholder="Enter the title" className="block w-full rounded-md border border-gray-300 p-3 text-sm text-gray-900 focus:border-blue-500 focus:ring-2 focus:ring-blue-500 dark:border-gray-600 dark:bg-gray-800 dark:text-white dark:placeholder-gray-400" {...register("title", { required: true })} />
</div>

<div className="flex flex-col gap-2">
    <label htmlFor="url" className="text-lg font-semibold text-gray-900 dark:text-white">
        URL
    </label>
    <input id="url" placeholder="Enter the URL" className="block w-full rounded-md border border-gray-300 p-3 text-sm text-gray-900 focus:border-blue-500 focus:ring-2 focus:ring-blue-500 dark:border-gray-600 dark:bg-gray-800 dark:text-white dark:placeholder-gray-400" {...register("url", { required: true })} />
</div>

<div className="flex flex-col gap-2">
    <label htmlFor="imageurl" className="text-lg font-semibold text-gray-900 dark:text-white">
        Image URL
    </label>
    <input id="imageurl" placeholder="Enter the image URL" className="block w-full rounded-md border border-gray-300 p-3 text-sm text-gray-900 focus:border-blue-500 focus:ring-2 focus:ring-blue-500 dark:border-gray-600 dark:bg-gray-800 dark:text-white dark:placeholder-gray-400" {...register("imageUrl", { required: true })} />
</div>

<div className="flex flex-col gap-2">
    <label htmlFor="theme" className="text-lg font-semibold text-gray-900 dark:text-white">
        Theme
    </label>
    <select id="theme" className="block w-full rounded-md border border-gray-300 p-3 text-sm text-gray-900 focus:border-blue-500 focus:ring-2 focus:ring-blue-500 dark:border-gray-600 dark:bg-gray-800 dark:text-white dark:placeholder-gray-400" {...register("theme", { required: true })}>
        <option value="javascript">JavaScript</option>
        <option value="typescript">TypeScript</option>
        <option value="react">React</option>
    </select>
</div>

<button type="submit" className="self-start mt-4 px-6 py-3 rounded-md bg-blue-700 text-white font-semibold text-sm hover:bg-blue-800 focus:outline-none focus:ring-4 focus:ring-blue-300 transition ease-in duration-200 dark:bg-blue-800 dark:hover:bg-blue-900">
    Create
</button>

</form>

         
       
      </>
    )
}




export default AddAnArticle