
import Head from "next/head"
import { useForm, SubmitHandler } from "react-hook-form"
import { useRouter } from "next/router";

type CollectionForm = {
    name: string;
    article: string[]
  };
  
const AddACollection = ()=> {

    const {
        register,
        handleSubmit,
        watch,
        formState: { errors },
      } = useForm<CollectionForm>()

      const onSubmit: SubmitHandler<CollectionForm> = (data) => console.log(data)
    return(
        <>
        
<Head>
          <title>create collection</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
       
            <h1 className="text-4xl">create collection</h1>
            <form
              className="flex flex-col gap-4"
              onSubmit={handleSubmit(onSubmit)}
            >
              <div>
                <label htmlFor="title"
                  className="mb-2 block text-sm font-medium text-gray-900 dark:text-white"
                >
                 name
                </label>
                <input
                  id="name"
                  className="block w-full rounded-lg border border-gray-300 bg-gray-50 p-2.5 text-sm text-gray-900 focus:border-blue-500 focus:ring-blue-500 dark:border-gray-600 dark:bg-gray-700 dark:text-white dark:placeholder-gray-400 dark:focus:border-blue-500 dark:focus:ring-blue-500"
                  {...register("name", { required: true })}
                />
              </div>
  
            
              <button
                type="submit"
                className="mb-2 mr-2 rounded-lg bg-blue-700 px-5 py-2.5 text-sm font-medium text-white hover:bg-blue-800 focus:outline-none focus:ring-4 focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
              >
                Create
              </button>
            </form>
         
       
      </>
    )
}




export default AddACollection